blueprint:
  name: Ikea I/O Media Control
  description: "Control your media with IKEA Tradfri on/off switch."
  domain: automation
  input:
    remote:
      name: Remote
      description: The remote that will control the music
      selector:
        device:
          integration: zha
          manufacturer: 'IKEA of Sweden'
          model: 'TRADFRI on/off switch'
    media_player:
      name: Media Player
      description: The media player that will be controlled
      selector:
        entity:
          domain: media_player
    play_action:
      name: Play action
      description: Action to run on I button press short
      default: []
      selector:
        action: {}
    volume_step:
      name: Volume step
      description: Volume step (volume between 0.00 and 1.00)
      default: 0.01
      selector:
        number:
          min: 0.0
          max: 0.2
          step: 0.01
          mode: slider
      stop_action:
        name: Stop action
        description: What to do on 0 button press short
        default: "Turn off"
        selector:
          select:
            options:
              - Turn off
              - Stop
              - Pause
              - Nothing
mode: restart
trigger:
- platform: event
  event_type: zha_event
  event_data:
    device_id: !input 'remote'
variables:
  command: "{{ trigger.event.data.command }}"
  cluster_id: "{{ trigger.event.data.cluster_id }}"
  endpoint_id: "{{ trigger.event.data.endpoint_id }}"
  media_player: !input media_player
  volume_step: !input volume_step
  max_repetitions: "{{ ( 1 / volume_step ) | int + 2 }}"
  stop_action: !input stop_action
action:
- choose:
  - conditions:
    - "{{ command == 'on' }}"
    - "{{ cluster_id == 6 }}"
    - "{{ endpoint_id == 1 }}"
    sequence: !input 'play_action'
  - conditions:
    - "{{ command == 'off' }}"
    - "{{ cluster_id == 6 }}"
    - "{{ endpoint_id == 1 }}"
    sequence:
    - service: media_player.turn_off
      target:
        entity_id: !input 'media_player'
  - conditions:
    - "{{ command == 'move_with_on_off' }}"
    - "{{ cluster_id == 8 }}"
    - "{{ endpoint_id == 1 }}"
    sequence:
      repeat:
        while:
        - condition: template
          value_template: "{{ repeat.index < max_repetitions }}"
        sequence:
        - service: media_player.volume_set
          target:
            entity_id: !input 'media_player'
          data_template:
            volume_level: '{{ state_attr(media_player, "volume_level") + volume_step }}'
        - delay: 1
  - conditions:
    - "{{ command == 'move' }}"
    - "{{ cluster_id == 8 }}"
    - "{{ endpoint_id == 1 }}"
    sequence:
      repeat:
        while:
        - condition: template
          value_template: "{{ repeat.index < max_repetitions }}"
        sequence:
        - service: media_player.volume_set
          target:
            entity_id: !input 'media_player'
          data_template:
            volume_level: '{{ state_attr(media_player, "volume_level") - volume_step }}'
        - delay: 1
  - conditions:
    - "{{ command == 'stop' }}"
    - "{{ cluster_id == 8 }}"
    - "{{ endpoint_id == 1 }}"
    sequence:
    - choose:
      - conditions:
        - "{{ stop_action == 'Turn off' }}"
        sequence:
        - service: media_player.turn_off
          target:
            entity_id: !input media_player
      - conditions:
        - "{{ stop_action == 'Stop' }}"
        sequence:
        - service: media_player.media_stop
          target:
            entity_id: !input media_player
      - conditions:
        - "{{ stop_action == 'Pause' }}"
        sequence:
        - service: media_player.media_pause
          target:
            entity_id: !input media_player
